// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
 const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'get-started',
    {
      type: 'category',
      label: 'Exploits',
      items: [
        'exploits/badrecovery',
        'exploits/sh1mmer',
        'exploits/e-halcyon'
      ],
    },
    'fakemurk',
    'finalizing-setup',
    'what-now',
    {
      type: 'category',
      label: 'Extras',
      items: [
        'extras/murkmod',
        'extras/fakeguardian',
        'extras/depthboot',
        'extras/lilac',
        'extras/ltbeef',
        'extras/cedr'
      ]
    },
    {
      type: 'category',
      label: 'Other',
      items: [
        'other/identify-wp',
        'other/choose-halcyon',
        'other/disable-wp-battery',
        'other/disable-wp-screw',
        'other/disable-wp-switch',
      ]
    },
         'exploits-legacy/get-started',
         {
             type: 'category',
             label: 'Exploits (Legacy)',
             items: [
                 'exploits-legacy/get-started',
                 'exploits-legacy/v101-crosh',
                 'exploits-legacy/v101',
                 'exploits-legacy/v81-crosh',
                 'exploits-legacy/v81-kiosk',
                 'exploits-legacy/v81',
                 'exploits-legacy/v87-crosh',
                 'exploits-legacy/v87',
                 'exploits-legacy/v91-crosh',
                 'exploits-legacy/v91'
             ],
         }
  ],
};

export default sidebars;
